CREATE TABLE TUSER(
	TUPK INT PRIMARY KEY,
	TUID VARCHAR(20) NOT NULL,
	TUPW VARCHAR(20) NOT NULL,
	TUROLE VARCHAR(20) NOT NULL,
	TUNICKNAME VARCHAR(20) NOT NULL,
	TUDEL INT DEFAULT 1,
	TUGENDER VARCHAR(20) NOT NULL,
	TUBIRTH VARCHAR(20) NOT NULL,
	TUPH VARCHAR(20) NOT NULL,
	TUADDRESSZIPCODE INT,
	TUADDRESS VARCHAR(150),
	TUADDRESSDETAIL VARCHAR(150),
	TUNATION VARCHAR(20) NOT NULL
);
CREATE TABLE TROOM(
	TRPK INT PRIMARY KEY,
	TRCATEGORY VARCHAR(30) NOT NULL,
	TRADDRESS VARCHAR(100) NOT NULL,
	TRREGION VARCHAR(20) NOT NULL,
	TRNAME VARCHAR(150) NOT NULL,
	TRPRICE INT NOT NULL,
	TRINFO VARCHAR(900) NOT NULL,
	TUPK INT,
	TRDEL INT DEFAULT 1,
	CHECKIN VARCHAR(20) NOT NULL,
	CHECKOUT VARCHAR(20) NOT NULL
);
CREATE TABLE TBOOK(
	TBPK INT PRIMARY KEY,
	TUPK INT NOT NULL,
	TRPK INT NOT NULL
);
CREATE TABLE TWISH(
	TWPK INT PRIMARY KEY,
	TUPK INT NOT NULL,
	TRPK INT NOT NULL
);
CREATE TABLE TREVIEW(
	TVPK INT PRIMARY KEY,
	TUPK INT NOT NULL,
	TRPK INT NOT NULL,
	TSTAR INT NOT NULL,
	TBOARD VARCHAR(300)
);
CREATE TABLE TREPLY(
	TPPK INT PRIMARY KEY,
	TUPK INT NOT NULL,
	TVPK INT NOT NULL,
	TPMSG VARCHAR(300) NOT NULL,
	CONSTRAINT TREVIEW_TREPLY FOREIGN KEY (TVPK) REFERENCES TREVIEW (TVPK) ON DELETE CASCADE
);